# Generated by Django 6.0.7 on 2026-07-20 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_sku', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=255)),
                ('pack_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(choices=[('g', 'Gram'), ('kg', 'Kilogram'), ('ml', 'Milliliter'), ('l', 'Liter'), ('each', 'Each')], max_length=10)),
                ('currency', models.CharField(choices=[('INR', 'Indian Rupee'), ('USD', 'US Dollar')], db_index=True, max_length=3)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='suppliers.supplier')),
            ],
            options={
                'db_table': 'products',
                'constraints': [models.UniqueConstraint(fields=('supplier', 'supplier_sku'), name='uq_supplier_supplier_sku'), models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='ck_product_price_non_negative'), models.CheckConstraint(condition=models.Q(('pack_size__gt', 0)), name='ck_product_pack_size_positive')],
            },
        ),
    ]
